Lambda-School-Labs/video-journal-for-teams-fe

yarn.lock
Fixes security vulnerability with the serialize-javascript package
=> Update serialize-javascript package vuln

.gitignore, src/App.test.js, src/__tests__/App.test.js
Adds initial testing suite and template for adding future tests to the front end.
=> Testing suite setup

src/App.js, src/components/DashboardNav.js, src/components/TeamCard.js, src/components/TeamList.js, src/components/UserDashboardContent.js, src/components/UserTeamsCard.js, src/components/UserTeamsList.js, src/components/UserVideosCard.js, src/components/UserVideosList.js, src/pages/UserDashboard.js, src/userdash.css
=> Ant.design and and preliminary styling added Userdashboard.

src/components/Login.js, src/components/Register.js, src/components/profile/tempStyles.css
1. added styling to register and login forms
2. added first and last name to register form
3. added token to register form
=> added basic styling to register and login forms

src/pages/Login.js, src/redux/actions/userActions.js
Fix issue that prevented logging in with email address.
=> Fix login with email functionality

src/redux/reducers/userReducer.js
Add missing userid on login/register
=> Add user id to store on login and register

src/components/UserDashboardContent.js, src/components/utils/LoadingView.js, src/index.js, src/redux/actions/userActions.js, src/redux/reducers/userReducer.js, src/redux/store.js
Added redux persist to store state and implemented logout functionality.
=> Add redux persist

src/redux/actions/userActions.js
Small fix missed from code review
=> Patch: Update userActions.js

src/components/team/EditMemberCard.js, src/components/team/MemberCard.js, src/components/team/MembersList.js, src/redux/actions/teamActions.js, src/redux/constants.js, src/redux/reducers/teamReducer.js
Completed functionality of deleting a user from a team on the frontend.
- [ x There are no merge conflicts
=> Delete user component

src/components/team/MembersList.js, src/redux/actions/teamActions.js, src/redux/constants.js, src/redux/reducers/teamReducer.js
Added a button on the team dashboard, so that a team manager can get an team member invite link.
Connected POST /api/invites to Redux
=> added invite link on team dashboard

.prettierrc, src/components/DashboardHeader.js
Add full name to dashboard header.
Add username on avatar hover.
=> Update dash header & avatar with fullname & username

src/components/team/MembersList.js, src/components/team/TeamDashboardContent.js
Added Team Name to Team Dashboard and did a slight refactor to make the TeamDashboardContent load the team data from the server instead of the MembersList component. MembersList still loads the team members.
=> Team name on team dashboard

src/components/team/MembersList.js
add team invitation full URL link, then have it copied to clipboard.
=> Add url invite

package.json, src/App.js
Updated the invite link path to match the invites created by the invite users button.
=> Updated path for invite link.

.github/workflow/ci.yml, README.md, codeclimate.yml, package.json
=> code climate setup

package.json, src/__tests__/App.test.js, src/__tests__/VideoDetails.test.js, src/setupTests.js
Adds test suite (3 tests) for the video details page.
=> Video details tests

src/components/team/PromptVideoList.js, src/redux/actions/teamActions.js, src/redux/constants.js, src/redux/reducers/teamReducer.js
1. made a button to create (POST) a new team prompt
2. modified redux files to conduct POST team prompt
3. also made 'add video' button that will link to video recording widget
=> Create Prompt on team dash

src/components/team/MembersList.js
=> changed invite link URL from free netlify to paid domain name

src/components/team/EditMemberCard.js
Add dynamic links for editing a user
=> show dynamic link to promote/demote user

src/App.js, src/components/team/PromptVideoList.js, src/pages/PostTeamVideo.js
Add page to record a video and view playback or download locally.
Add initial upload functionality (untested)
Next up will be to finish functionality, refactoring into more components, styling and writing tests.
=> Initial Video capture & upload functionality

README.md
Updated readme documentation
(ignore the old branch name for google analytics, forgot to checkout the documentation branch)
=> updated readme doc

src/components/team/EditMemberCard.js, src/redux/actions/teamActions.js, src/redux/constants.js, src/redux/reducers/teamReducer.js
Allow user to be able to update team member's role
=> Update role for a user

public/index.html
updated public html google analytics script
=> modified google analytic script

src/pages/PostTeamVideo.js
=> changes to sync video form data to backend.

src/components/team/EditMemberCard.js, src/components/team/MemberCard.js, src/components/team/MembersList.js, src/components/team/PromptVideoList.js, src/components/team/TeamDashboardContent.js, src/redux/actions/teamActions.js, src/redux/actions/userActions.js, src/redux/reducers/teamReducer.js
Added response to all actions in catch block.
Fix bug when switching roles for team members.
=> added .response to error payload

src/App.scss, src/components/user/UserVideosCard.js, src/scss/global.scss, src/scss/video-card.scss, src/userdash.css
=> Style video card

src/components/team/MembersList.js, src/components/team/PromptCard.js, src/components/team/teamTest.css, src/components/user/UserTeamsList.js, src/components/user/UserVideosList.js, src/scss/global.scss, src/scss/member-list.scss
=> style tweaks

src/__tests__/TeamDash.test.js
corrected team dash test for render "prompts"
=> fixed team dash prompt test

src/components/user/UserTeamsList.js, src/redux/actions/teamActions.js
=> Fix for Create Team button.

public/index.html, src/App.js, src/components/user/UserVideosCard.js, src/scss/auth.scss, src/scss/carousel.scss, src/scss/global.scss
=> Responsive auth pages

src/components/team/AddPromptModal.js, src/components/team/InviteModal.js, src/components/team/MembersList.js, src/components/team/PromptCard.js, src/components/team/PromptModal.js, src/components/team/PromptVideoList.js, src/components/utils/CopyClipboard.js
1. added Ant form validation for adding a new prompt
2. abstracted out prompt modal into new component
3. added record video button link to post new video page
=> Prompt & video list adjustments

src/components/team/AddPromptModal.js, src/components/team/InviteModal.js, src/components/team/MembersList.js, src/components/team/PromptCard.js, src/components/team/PromptModal.js, src/components/team/PromptVideoList.js, src/components/utils/CopyClipboard.js
1. made team invite modal component
2. made copy clipboard utils component
=> Invite modal

src/components/user/UserTeamsCard.js, src/components/user/UserTeamsList.js, src/components/user/UserVideosCard.js, src/components/user/UserVideosList.js, src/redux/actions/userActions.js, src/scss/team-card.scss
Completed styling for TeamCard
=> Team card styling

src/components/VideoDetails/VideoPlayer.js, src/pages/VideoDetails.js, src/scss/video-card.scss
video player widget is now size-responsive.
=> added media query breakpoints to the media player widget.

src/components/profile/ProfileForm.js
=> Remove error state

src/App.scss, src/components/user/UserVideosCard.js, src/components/user/UserVideosList.js
=> Quick fix.

src/components/PostTeamVideo/RecordStream/RecordStream.js, src/components/VideoDetails/VideoPlayer.js, src/components/user/UserVideosCard.js, src/scss/post-video.scss
=> Fixed overriding style.

src/App.js, src/components/PostTeamVideo/PostVideoModal.js, src/components/PostTeamVideo/RecordStream/RecordStream.js, src/components/PostTeamVideo/UploadVideo/UploadProgress.js, src/components/VideoDetails/VideoPlayer.js, src/components/user/UserTeamsList.js, src/components/user/UserVideosCard.js, src/redux/actions/teamActions.js, src/scss/post-video.scss
=> Post video fixes

src/components/team/EditMemberCard.js, src/scss/auth.scss
Tweaks login / signup button color to AlpacaGreen along with the member promote/demote icon color.
=> UI login/signup button color tweak

src/App.js
Fixes deploy failure in netlify due to missing file reference
=> Remove unused import from app

.codeclimate.yml
=> Add threshold update to code climate

src/scss/user-profile.scss
Fixed form from overlapping footer when panel opens.
=> small style fix

package.json, src/components/user/UserVideosCard.js
Fixes video card description. Originally it rendered the description text twice. Now it's only once, as intended.
=> Fix video description duplication issue

README.md
Adds correct README badges (netlify build status, react version)
=> Update readme with proper badges

src/pages/Home.js, src/scss/home.scss, src/scss/variables.scss
Added "team" info to landing page.
=> Landing page

src/components/shared/Carousel.js, src/components/team/PromptList.js, src/components/user/UserVideosList.js
Added "No Data" image to lists when they're empty.
=> Empty component

README.md, package.json, src/App.js, src/components/team/PromptList.js, src/pages/TeamDashboard.js, src/redux/actions/userActions.js, src/socket/socket.js
Created socket connection for real time video uploads
=> Prem feature websocket fe

.vscode/settings.json, src/components/VideoDetails/Feedback.js, src/components/VideoDetails/FeedbackForm.js, src/components/team/AddPromptModal.js, src/components/team/PromptList.js, src/components/utils/CopyClipboard.js, src/pages/TeamDashboard.js, src/pages/VideoDetails.js
=> Isabella email

package.json, src/__tests__/TeamDash.test.js, src/__tests__/UserDashboard.test.js, src/components/VideoDetails/Feedback.js, src/components/user/UserVideosCard.js, src/components/user/UserVideosList.js, src/pages/TeamDashboard.js
=> Chris websocketsfe

package.json, src/App.scss, src/__tests__/TeamDash.test.js, src/__tests__/VideoDetails/Feedback.test.js, src/components/PostTeamVideo/PostVideoModal.js, src/components/VideoDetails/Feedback.js, src/components/VideoDetails/FeedbackTable.js, src/components/nav/DashboardHeader.js, src/components/nav/NotificationNav.js, src/components/profile/ProfileForm.js, src/components/user/UserVideosCard.js, src/pages/TeamDashboard.js, src/pages/UserDashboard.js, src/pages/VideoDetails.js, src/redux/actions/userActions.js, src/redux/constants.js, src/redux/reducers/userReducer.js, src/scss/nav-header.scss, src/scss/utility.scss, src/scss/variables.scss
=> Chris notify

package-lock.json, src/pages/Invite.js
=> history push

src/components/nav/DashboardHeader.js, src/components/nav/DashboardNav.js, src/components/nav/NotificationNav.js, src/components/user/UserTeamsList.js, src/components/user/UserVideosCard.js, src/components/user/UserVideosList.js, src/pages/UserDashboard.js, src/redux/actions/userActions.js
=> fixed registraion

src/components/nav/DashboardNav.js
=> fixed dashboard link bug

src/components/organization/OrgEditMemberCard.js, src/components/organization/OrgMemberCard.js, src/components/team/EditMemberCard.js, src/pages/OrganizationUsers.js, src/redux/actions/organizationActions.js, src/redux/actions/teamActions.js, src/redux/constants.js, src/redux/reducers/organizationReducer.js
=> Org role update

src/App.js, src/redux/actions/userActions.js
=> team redirect issue fixed

src/components/nav/NotificationNav.js, src/pages/VideoDetails.js, src/redux/actions/userActions.js
=> fixed notification bell issue

src/App.js, src/components/PostTeamVideo/UploadVideo/UploadProgress.js, src/components/VideoDetails/FeedbackForm.js, src/components/VideoDetails/VideoPlayer.js, src/components/nav/DashboardHeader.js, src/components/nav/DashboardNav.js, src/components/nav/NotificationNav.js, src/components/organization/OrgEditMemberCard.js, src/components/profile/Dropzone.js, src/components/team/AddPromptModal.js, src/components/team/EditMemberCard.js, src/components/team/MemberCard.js, src/components/team/MembersList.js, src/components/user/UserTeamsList.js, src/pages/Invite.js, src/pages/TeamDashboard.js, src/pages/UserDashboard.js, src/pages/VideoDetails.js, src/redux/actions/organizationActions.js, src/redux/actions/teamActions.js, src/redux/actions/userActions.js, src/redux/constants.js, src/redux/reducers/teamReducer.js
=> Yellow screen

src/components/okta/OktaLogin.js, src/components/team/EditTeam.js, src/components/team/MembersList.js, src/index.js, src/pages/TeamDashboard.js, src/redux/actions/teamActions.js, src/redux/constants.js
=> added edit and delete functionality for teams

src/index.js
=> changes to okta login

src/index.js
=> more changes to otka

src/components/VideoDetails/QuestionsForm.js, src/redux/actions/userActions.js
=> adds feedback with star system

src/components/VideoDetails/QuestionsForm.js
=> fixes name not being correct on comments

public/index.html, src/App.js, src/components/charts/BarGraph.js, src/components/charts/Charts.js, src/components/charts/LineGraph.js
=> staging for final merge
